services:
  nginx:
    ports:
      - '${APP_PORT:-8089}:80'

  mysql:
    ports:
      - '${DB_PORT:-3306}:3306'

  php-fpm:
    build:
      args:
        - WITH_XDEBUG=${WITH_XDEBUG:-true}
    volumes:
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
